name: Reader
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.example.reader
    DEVELOPMENT_TEAM: ""
packages:
  ReaderKit:
    path: Packages/ReaderKit

targets:
  ReaderApp:
    type: application
    platform: iOS
    info:
      path: App/Info.plist
    sources:
      - path: App/Sources
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
        CODE_SIGNING_ALLOWED: "NO"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_IDENTITY: ""
    dependencies:
      - package: ReaderKit
        product: ReaderUI

  ReaderAppTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: App/Tests/Info.plist
    sources:
      - path: App/Tests
    dependencies:
      - target: ReaderApp

  ReaderCoreUnitTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: App/Tests/Info.plist
    sources:
      - path: Packages/ReaderKit/Tests/ReaderCoreTests
    dependencies:
      - package: ReaderKit
        product: ReaderCore

  ReaderUISnapshotTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: App/Tests/Info.plist
    sources:
      - path: Packages/ReaderKit/Tests/ReaderUITests
    dependencies:
      - package: ReaderKit
        product: ReaderUI
      - package: ReaderKit
        product: ReaderCore

schemes:
  ReaderApp:
    build:
      targets:
        ReaderApp: all
    test:
      targets:
        - ReaderAppTests
        - ReaderCoreUnitTests
        - ReaderUISnapshotTests
