name: Reader
options:
  bundleIdPrefix: com.splap
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.splap.reader
packages:
  ReaderKit:
    path: Packages/ReaderKit

targets:
  ReaderApp:
    type: application
    platform: iOS
    info:
      path: App/Info.plist
    sources:
      - path: App/Sources
      - path: App/Resources
        buildPhase: resources
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
        CODE_SIGNING_ALLOWED: "YES"
        CODE_SIGNING_REQUIRED: "YES"
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
    dependencies:
      - package: ReaderKit
        product: ReaderUI

  ReaderAppTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: App/Tests/Info.plist
    sources:
      - path: App/Tests
    dependencies:
      - target: ReaderApp

  ReaderCoreUnitTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: App/Tests/Info.plist
    sources:
      - path: Packages/ReaderKit/Tests/ReaderCoreTests
    dependencies:
      - package: ReaderKit
        product: ReaderCore

  ReaderUISnapshotTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: App/Tests/Info.plist
    sources:
      - path: Packages/ReaderKit/Tests/ReaderUITests
    dependencies:
      - package: ReaderKit
        product: ReaderUI
      - package: ReaderKit
        product: ReaderCore

  ReaderAppUITests:
    type: bundle.ui-testing
    platform: iOS
    info:
      path: App/Tests/Info.plist
    sources:
      - path: App/UITests
    dependencies:
      - target: ReaderApp

schemes:
  ReaderApp:
    build:
      targets:
        ReaderApp: all
    test:
      targets:
        - ReaderAppTests
        - ReaderCoreUnitTests
        - ReaderUISnapshotTests

  ReaderAppUITests:
    build:
      targets:
        ReaderApp: all
        ReaderAppUITests: [test]
    test:
      targets:
        - ReaderAppUITests
